num_iterations: 20
keep_history_on_memory: true
write_history_dir: ../output/face/optimization_histories
graph_conf:
  edges_k: 6
  num_nodes_per_point: 4
  weight_type: inv
  sigma: null
  eps: 1.0e-08
correspondence_conf:
  k: 1
minimization_conf:
  learning_rate: 0.0001
  max_iters: 50
  w_chamfer: 1.0
  w_landmark: 1.0
  w_arap: 1.0
  w_edge_length_uniform: 0.0
  w_normal_consistency: 0.0
  trunc_th: -1.0
  eps: 1.0e-07
  fix_anchors: true
  report_interval: 10
